version: '3.9'

services:
  db:
    image: postgres:15
    container_name: safepass-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sudden
      POSTGRES_PASSWORD: Alex210528062207!
      POSTGRES_DB: bd_safepass
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app
      - /app/node_modules
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    restart: always

volumes:
  db-data:
